

all: ComparingCpuSc.o
	@echo "Sucessfully compiled"
	@./ComparingCpuSc.o

ComparingCpuSc.o: ComparingCpuSc.c
	@echo "Compiling CPU scheduling comparison program."
	@gcc -g ComparingCpuSc.c -o ComparingCpuSc.o
	
clean:
	@rm ComparingCpuSc.o